### ISSUE TITLE
Intellisense stopped working with a UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dave-multiplier** [lightyen/vscode-tailwindcss-twin#14]
This extension worked fine until last night, but today morning, when I try to use it, it doesn't give me Intellisense anymore.
Instead, I get the following in the debug console

```
UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at flattenColorPalette (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\util\flattenColorPalette.js:8:67)
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\plugins\caretColor.js:27:48
    at registerPlugins (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupContextUtils.js:487:7)
    at createContext (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupContextUtils.js:530:3)
    at getContext (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupContextUtils.js:591:17)
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupTrackingContext.js:177:57
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\processTailwindFeatures.js:54:7
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\index.js:25:56
    at LazyResult.runOnRoot (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\postcss\lib\lazy-result.js:339:16)
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:12464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:12464) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Option: `separator` forced to be set ':'.
(node:12464) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at flattenColorPalette (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\util\flattenColorPalette.js:8:67)
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\plugins\caretColor.js:27:48
    at registerPlugins (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupContextUtils.js:487:7)
    at createContext (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupContextUtils.js:530:3)
    at getContext (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupContextUtils.js:591:17)
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\lib\setupTrackingContext.js:177:57
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\processTailwindFeatures.js:54:7
    at c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\tailwindcss\lib\jit\index.js:25:56
    at LazyResult.runOnRoot (c:\Users\dave\.vscode\extensions\lightyen.tailwindcss-intellisense-twin-0.9.0\node_modules\postcss\lib\lazy-result.js:339:16)
(node:12464) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4) 
```

Any idea how I can get this fixed?

**Comment by lightyen** [comment]
I have no idea, maybe you have a broken tailwind.config like this:
```js
module.exports = {
  theme: {
    caretColor: null,
  },
}
```

Can you share your config file?

**Comment by dave-multiplier** [comment]
I cannot actually share the config because I'm working on a proprietary codebase. But I don't think anything could be wrong with that because the plugin was working till yesterday and we haven't made any changes to it in many days.
Is there any way I can find out where in the config file might be causing this?
Any way I can dive more deeper into this and debug it?

**Comment by r0zar** [comment]
My team's twin.macro Intellisense stopped working recently too. Although it does still work when using the className props with the Tailwind CSS Intellisense extension.

**Comment by r0zar** [comment]
```
(node:12164) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at flattenColorPalette (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/util/flattenColorPalette.js:8:67)
    at /home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/plugins/caretColor.js:27:48
    at registerPlugins (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:487:7)
    at createContext (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:530:3)
    at getContext (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:591:17)
    at /home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/jit/lib/setupTrackingContext.js:177:57
    at /home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:54:7
    at /home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/tailwindcss/lib/jit/index.js:25:56
    at LazyResult.runOnRoot (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.0/node_modules/postcss/lib/lazy-result.js:339:16)
(node:12164) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

**Comment by dave-multiplier** [comment]
With no change to the config file, Intellisense started working again.
I am closing this because it seems to be fixed. I'm guessing it had something to do with the latest release.
Thanks 🙏🏻

**Comment by lightyen** [comment]
https://github.com/tailwindlabs/tailwindcss/commit/8ceedb2dd64b7e99f6a6de7f6fb68ac65d66d862
