### ISSUE TITLE
Getting error on startup

### ISSUE THREAD

**Issue by r0zar** [lightyen/vscode-tailwindcss-twin#16]
Thanks for building/supporting this extension btw.

I'm now getting this error when starting up with the extension installed.

```
(node:41563) UnhandledPromiseRejectionWarning: TypeError: getProcessedPlugins is not a function
    at /home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.2/node_modules/tailwindcss/lib/processTailwindFeatures.js:83:83
    at LazyResult.runOnRoot (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.2/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.2/node_modules/postcss/lib/lazy-result.js:391:26)
    at LazyResult.async (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.2/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/home/rozar/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.9.2/node_modules/postcss/lib/lazy-result.js:206:17)
    ```

**Comment by lightyen** [comment]
I can't reproduce it.

**Comment by r0zar** [comment]
Made no changes, but it working again.

FYI, this affected my ubuntu desktop but not my macbook, not sure if that helps.

Closing since it's resolved.
