### ISSUE TITLE
Yarn 2 PnP compatibility broken from v0.11.7 onwards

### ISSUE THREAD

**Issue by Interpause** [lightyen/vscode-tailwindcss-twin#32]
Thanks for creating this useful extension. I typically use Yarn 2's PnP feature for my projects. Recently, I've noticed that from v0.11.7 onwards, when falling back to `tailwindcss/defaultConfig`, I receive the following error:

```
[3/24/2022, 1:02:33 PM] [error] Error: The locator that owns the "/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/node_modules/lodash/cloneDeep.js" path can't be found inside the dependency tree (this is probably an internal error)
    at makeError (/home/user/Documents/Projects/project/.pnp.cjs:12887:34)
    at applyNodeExportsResolution (/home/user/Documents/Projects/project/.pnp.cjs:13496:13)
    at resolveUnqualifiedExport (/home/user/Documents/Projects/project/.pnp.cjs:13841:35)
    at resolveRequest (/home/user/Documents/Projects/project/.pnp.cjs:13898:101)
    at Object.resolveRequest (/home/user/Documents/Projects/project/.pnp.cjs:13955:26)
    at requireModule (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\common\module.ts:70:20)
    at Module.C.Q.require (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\common\module.ts:186:10)
    at h (/opt/vscode/resources/app/out/vs/loader.js:4:699)
    at Object.<anonymous> (<anonymous>:2:19)
    at Module.u._compile (/opt/vscode/resources/app/out/vs/loader.js:4:1313)
    at requireModuleFromCode (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\common\module.ts:189:11)
    at Object.f [as importFrom] (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\common\module.ts:288:6)
    at Object.readTailwindConfig (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\service\tailwind\index.ts:1:38)
    at start (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\service\index.ts:116:10)
    at wait (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\service\index.ts:268:19)
    at onDocumentColors (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\service\index.ts:239:10)
    at Object.provideDocumentColors (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\service\index.ts:65:11)
    at Object.provideDocumentColors (/home/user/.vscode/extensions/lightyen.tailwindcss-intellisense-twin-0.12.2/dist/C:\Users\lightyen\vscode-tailwindcss-twin\src\client.ts:167:37)
    at Q.provideColors (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:112148)
    at /opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:129326
    at be._withAdapter (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:116655)
    at be.$provideDocumentColors (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:129304)
    at n._doInvokeHandler (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13812)
    at n._invokeHandler (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13496)
    at n._receiveRequest (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12107)
    at n._receiveOneMessage (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10836)
    at /opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8945
    at d.invoke (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.fire (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at c.fire (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19017)
    at /opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34267
    at d.invoke (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.fire (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at c.fire (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19017)
    at s._receiveMessage (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23598)
    at /opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21132
    at d.invoke (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.fire (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at w.acceptChunk (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15848)
    at /opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14978
    at Socket.P (/opt/vscode/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13790)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Switching back to v0.11.6 of the extension, the default config loads fine and the extension works as expected. Looking at the extension changelog, in v0.11.7 some yarn 2 enhancement was added. Could that have broken something?

Interestingly, if I create a empty tailwind.config.js that contains only `module.exports = {}`, the extension loads normally.

**Comment by lightyen** [comment]
Fixed in 604ccec20f0366bcff9e5df8f0af74bf959420fd
